添加设置cl到环境变量

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -117,6 +117,27 @@ jobs:
         echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $env:GITHUB_ENV
         echo "VCPKG_FEATURE_FLAGS=versions" >> $env:GITHUB_ENV
 
+    - name: Add cl To Path
+      if: matrix.os == 'windows-latest'
+      shell: pwsh
+      run: |
+        # 设置 Visual Studio 的环境变量
+        $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
+        if (-not (Test-Path -Path $vswherePath)) {
+          echo "vswhere.exe not found. Visual Studio may not be installed correctly."
+          exit 1
+        }
+        $vsInstallPath = & $vswherePath -latest -property installationPath
+        $vcvarsallPath = Join-Path -Path $vsInstallPath -ChildPath "\VC\Auxiliary\Build\vcvarsall.bat"
+        if (-not (Test-Path -Path $vcvarsallPath)) {
+          echo "vcvarsall.bat not found. Visual Studio may not be installed correctly."
+          exit 1
+        }
+        cmd /c "`"$vcvarsallPath`" x64"
+        echo "MSVC Compiler version:"
+        cl /?
+        if ($LASTEXITCODE -ne 0) { exit 1 }
+
     - name: Test Tools Windows
       if: matrix.os == 'windows-latest'
       run: |
